[package]
name = "mba-device"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
embedded-graphics.workspace = true
mba-protocol = { path = "../mba-protocol" }
rppal.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
